repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
      - id: ruff-format

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: poetry-lock
        name: poetry-lock
        entry: poetry lock --check
        language: system
        pass_filenames: false
        files: ^pyproject.toml$
        types: [file]
        # This hook should run after any other hooks that might modify pyproject.toml
        # For example, if you had a hook that auto-sorted dependencies in pyproject.toml

  # Optional: Uncomment to run pytest before every commit
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: poetry run pytest
  #       language: system
  #       pass_filenames: false
