name: Build & Publish (Poetry)

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest       # un solo runner basta
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install poetry

      # ‼️ instala los wheels binarios de NumPy/SciPy antes del build
      - name: Pre-install heavy deps
        run: |
          python -m pip install --only-binary=:all: numpy scipy

      - name: Build with Poetry
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}